# Generated by Django 2.2.6 on 2020-01-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
