# Generated by Django 2.2.6 on 2020-01-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200116_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='outofmid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='sub1mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='sub2mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='sub3mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='sub4mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='sub5mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='subject1',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='subject2',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='subject3',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='subject4',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='subject5',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
