# Generated by Django 2.2.6 on 2020-01-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200118_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='remidsub1mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='remidsub2mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='remidsub3mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='remidsub4mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enroll',
            name='remidsub5mark',
            field=models.IntegerField(null=True),
        ),
    ]
