# Generated by Django 2.2.6 on 2020-01-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200118_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='outofmidsub2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='outofmidsub3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='outofmidsub4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='outofmidsub5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='remidsub2mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='remidsub3mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='remidsub4mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='remidsub5mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='sub2mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='sub3mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='sub4mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='sub5mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='subject2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='subject3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='subject4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='subject5',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
