# Generated by Django 2.2.6 on 2020-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200119_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='remidsub1mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
