# Generated by Django 2.2.6 on 2020-02-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200119_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='outofmidsub1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='sub1mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
