# Generated by Django 2.2.6 on 2020-02-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200201_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='enno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
