# Generated by Django 2.2.6 on 2020-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200201_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='enno',
            field=models.TextField(max_length=12, null=True),
        ),
    ]
